
services:
  - type: web
    name: crack-inspection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_crack_inspection_clean_with_dashboard.py --server.port=$PORT --server.enableCORS=false
    plan: free
